"""on delete

Revision ID: 9ac281555c75
Revises: 6532c6a659be
Create Date: 2025-04-04 11:58:00.679546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac281555c75'
down_revision: Union[str, None] = '6532c6a659be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('source_newsletter_config_association_newsletter_config_id_fkey', 'source_newsletter_config_association', type_='foreignkey')
    op.drop_constraint('source_newsletter_config_association_source_id_fkey', 'source_newsletter_config_association', type_='foreignkey')
    op.create_foreign_key(None, 'source_newsletter_config_association', 'newsletter_config', ['newsletter_config_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'source_newsletter_config_association', 'source', ['source_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source_newsletter_config_association', type_='foreignkey')
    op.drop_constraint(None, 'source_newsletter_config_association', type_='foreignkey')
    op.create_foreign_key('source_newsletter_config_association_source_id_fkey', 'source_newsletter_config_association', 'source', ['source_id'], ['id'])
    op.create_foreign_key('source_newsletter_config_association_newsletter_config_id_fkey', 'source_newsletter_config_association', 'newsletter_config', ['newsletter_config_id'], ['id'])
    # ### end Alembic commands ###
