"""title slug image

Revision ID: 653ecff6b24c
Revises: 5a7507c06df1
Create Date: 2025-04-04 14:31:04.416900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653ecff6b24c'
down_revision: Union[str, None] = '5a7507c06df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletter', sa.Column('title', sa.String(), nullable=False))
    op.add_column('newsletter', sa.Column('slug', sa.String(), nullable=False))
    op.add_column('newsletter', sa.Column('image_url', sa.String(), nullable=False))
    op.add_column('newsletter_config', sa.Column('slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newsletter_config', 'slug')
    op.drop_column('newsletter', 'image_url')
    op.drop_column('newsletter', 'slug')
    op.drop_column('newsletter', 'title')
    # ### end Alembic commands ###
