"""is_archived

Revision ID: 6532c6a659be
Revises: 32dcbabd034b
Create Date: 2025-04-04 11:56:35.077477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6532c6a659be'
down_revision: Union[str, None] = '32dcbabd034b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletter_config', sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newsletter_config', 'is_archived')
    # ### end Alembic commands ###
