"""llm_configs

Revision ID: 4d72969529e3
Revises: 2c7187a7cb52
Create Date: 2025-04-04 07:52:27.129063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d72969529e3'
down_revision: Union[str, None] = '2c7187a7cb52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_config',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('api_key_name', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.String(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('uq_extract_name_content_id', 'extract', type_='unique')
    op.create_unique_constraint('uq_extract_source_id_content_id', 'extract', ['source_id', 'content_id'])
    op.add_column('newsletter_config', sa.Column('llm_config_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'newsletter_config', 'llm_config', ['llm_config_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'newsletter_config', type_='foreignkey')
    op.drop_column('newsletter_config', 'llm_config_id')
    op.drop_constraint('uq_extract_source_id_content_id', 'extract', type_='unique')
    op.create_unique_constraint('uq_extract_name_content_id', 'extract', ['name', 'content_id'])
    op.drop_table('llm_config')
    # ### end Alembic commands ###
