"""output

Revision ID: 32dcbabd034b
Revises: d2d576a371f6
Create Date: 2025-04-04 10:49:22.189266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32dcbabd034b'
down_revision: Union[str, None] = 'd2d576a371f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletter', sa.Column('output_markdown', sa.Text(), nullable=False))
    op.add_column('newsletter', sa.Column('output_html', sa.Text(), nullable=False))
    op.drop_column('newsletter', 'output_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletter', sa.Column('output_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('newsletter', 'output_html')
    op.drop_column('newsletter', 'output_markdown')
    # ### end Alembic commands ###
